name: Main Workflow
on: [push]
jobs:
  build-gcc:
    name: Build
    strategy:
      matrix:
        go-version: [1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.10, 1.11, 1.12, 1.13, 1.14, 1.15]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.go-version }}
    steps:
      - uses: actions/checkout@v1
      - run: go version
      - run: go get -t -v ./...
      - run: go test -v ./...
