name: Main Workflow
on:
  push:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build:
    name: Build
    timeout-minutes: 10
    strategy:
      matrix:
        go-version: [
          "1.11",
          "1.12",
          "1.13",
          "1.14",
          "1.15"
        ]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.go-version }}
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v4
      - name: Create directories
        run: |
          cd ..
          mkdir -p ~/gopath/src/github.com/joamag
          cp -rp goers ~/gopath/src/github.com/joamag
      - name: Print Go information
        run: go version
      - name: Build package
        run: cd ~/gopath && GOPATH=~/gopath go get -t -v ./...
      - name: Run unit tests
        run: cd ~/gopath && GOPATH=~/gopath go test -v ./...
  build-neo:
    name: Build Neo
    timeout-minutes: 10
    strategy:
      matrix:
        go-version: [
          "1.16",
          "1.17",
          "1.18",
          "1.19",
          "1.20",
          "1.21"
        ]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.go-version }}
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v4
      - name: Print Go information
        run: go version
      - name: Build Main
        run: go build -buildvcs=false
        if: matrix.go-version != '1.16' && matrix.go-version != '1.17'
      - name: Build Goers
        run: cd src/goers && go build
      - name: Build Goers Run
        run: cd src/goers-run && go build -buildvcs=false
        if: matrix.go-version != '1.16' && matrix.go-version != '1.17'
      - name: Run unit tests
        run: cd src/goers && go test
