name: Main Workflow
on:
  push:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build-gcc:
    name: Build
    timeout-minutes: 10
    strategy:
      matrix:
        go-version: [
          "1.2",
          "1.3",
          "1.4",
          "1.5",
          "1.6",
          "1.7",
          "1.8",
          "1.9",
          "1.10",
          "1.11",
          "1.12",
          "1.13",
          "1.14",
          "1.15",
          "1.16",
          "1.17",
          "1.18",
          "1.19"
        ]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.go-version }}
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v3
      - name: Create directories
        run: |
          cd ..
          mkdir -p ~/gopath/src/github.com/joamag
          cp -rp goers ~/gopath/src/github.com/joamag
      - name: Print Go information
        run: go version
      - name: Build package
        run: cd ~/gopath && GOPATH=~/gopath go get -t -v ./...
      - name: Run unit tests
        run: cd ~/gopath && GOPATH=~/gopath go test -v ./...
